### ISSUE TITLE
Recursinve array allocation proceedure causing error TS(2345)

### ISSUE THREAD

**Issue by Republicof1** [tsastro/tsofa#1]
Error "Argument of type 'never[] | 0' is not assignable to parameter of type 'never'.  
Type 'never[]' is not assignable to type 'never'." 

a number of places across the TSOFA and test files.

**Comment by pahjbo** [comment]
what is the context of these errors?

```
yarn build
```

reports no errors.

**Comment by Republicof1** [comment]
it replates to an ambiguity when the a variable is set to the nothing type.
It is likely to be a compile only error because javascript wont care.

let x = [] implies a type of nothing and nothing[] so the compiler highlights the ambiguity.

using let x = new Array() makes the type any[] which is the most permissive type, avoiding this ambiguity

**Comment by pahjbo** [comment]
this was fixed with the single function that was actually better typed to be number[][]
